
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myschema?serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
      enabled: true
      encoding: utf-8
      prefix: classpath:/templates/
      cache: false
      mode: LEGACYHTML5
      suffix: .html

mybatis-plus:
  typeAliasesPackage: com.example.hello.po

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.hello.po
