spring:
  application:
#    name: eureka-client-homepage-course
    name: eureka-client-energy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/myschema?serverTimezone=UTC
    username: root
    password: lin85565335
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.ld.homepage.entity

server:
  port: 8000
